import { CaseStudy } from '../types';

export const evidenceCaseStudies: CaseStudy[] = [
  {
    id: 'case_1',
    title: 'The Silent 8-Month Post-Launch Deletion Purge',
    subtitle: 'App with $14.2k MRR unlisted with 48 hours notice because Delete Account required sending an email instead of a 1-tap in-app trigger.',
    appNamePlaceholder: 'Popular iOS Fitness & Workout Log',
    category: 'account_deletion',
    platform: 'ios',
    year: '2024',
    ruleBroken: 'Apple App Store Guideline 5.1.1(v) - In-App Account Deletion',
    revenueImpact: '$11,400 Lost Revenue • 14 Days Delisted',
    daysDowntime: 14,
    sourceType: 'Reddit',
    fullStory: `An indie developer with a profitable fitness tracker woke up on a Tuesday to an email titled "Your app has been removed from sale on the App Store". The app had passed Apple review 7 times over 9 months without complaint. 

However, during a routine background compliance re-audit, Apple's automated crawler flagged that the "Delete Account" button in settings directed users to a mailto:support@... link rather than completing the deletion directly in the app.

Because the app was unlisted, all active App Store Search Ads paused, organic ranking dropped from #4 to #118 in Health & Fitness, and recurring subscription churn surged by 19%. It took 14 days to deploy backend API deletion endpoints, push a new build, and get the appeal reviewed.`,
    developerQuote: `"Apple approved our app 7 times over 9 months. Then on a random Tuesday, our entire business was wiped from the App Store overnight for a button we thought was already compliant. It cost us over $11,000 and 2 weeks of absolute panic."`,
    keyTakeaway: 'Apple requires in-app deletion to actually initiate data purge immediately—never hide behind emails, forms, or delayed manual tickets.',
    preventionCode: `// StoreGuard Rule: APP-RULE-DEL-511
// StoreGuard automatically scans UI tree for "Delete Account" buttons and verifies backend API calls.`
  },
  {
    id: 'case_2',
    title: 'The Great Spring 2024 Privacy Manifest Rejection Wave',
    subtitle: 'Over 1,200 indie apps rejected on TestFlight/App Store submission due to third-party SDKs using statfs() and gettimeofday() without NSPrivacyAccessedAPITypes declarations.',
    appNamePlaceholder: 'Markdown Notes & Task Manager',
    category: 'privacy_manifest',
    platform: 'ios',
    year: '2024',
    ruleBroken: 'Apple Required Reason API Enforcement (ITMS-91053)',
    revenueImpact: '$4,800 Launch Delay • Missed Product Hunt #1 Window',
    daysDowntime: 5,
    sourceType: 'HackerNews',
    fullStory: `When Apple turned on mandatory Privacy Manifest checks in May 2024, thousands of indie developers uploading new builds were hit with automatic binary upload rejections (Error ITMS-91053).

The developer of a popular note-taking app had scheduled their big 2.0 release on Product Hunt and Twitter. When uploading the release binary the night before, App Store Connect rejected it because an old version of a logging pod accessed system file timestamps without a declared reason code in PrivacyInfo.xcprivacy.

Scrambling to debug Mach-O symbols at 3 AM resulted in postponing the launch and missing their media coverage.`,
    developerQuote: `"We had press lined up and 3,000 people on our waitlist. App Store Connect blocked our build at 11 PM because an analytics SDK we barely used didn't have an xcprivacy file. StoreGuard would have caught this 2 weeks ago in CI."`,
    keyTakeaway: 'Always generate a verified PrivacyInfo.xcprivacy that covers all required reason APIs used by both your own code and CocoaPods/SPM dependencies.',
    preventionCode: `<!-- Automated Privacy Manifest Generator generated by StoreGuard -->
<key>NSPrivacyAccessedAPITypes</key>
<array>
  <dict>
    <key>NSPrivacyAccessedAPIType</key>
    <string>NSPrivacyAccessedAPICategoryFileTimestamp</string>
    <key>NSPrivacyAccessedAPITypeReasons</key>
    <array><string>C617.1</string></array>
  </dict>
</array>`
  },
  {
    id: 'case_3',
    title: 'Google Play 14-Day Ultimatum: The Data Safety Form Trap',
    subtitle: 'A single unchecked box for Advertising ID (AD_ID) triggered an automated 30-day suspension warning from Google Play Console.',
    appNamePlaceholder: 'Android AI Photo Editor & Filters',
    category: 'data_safety',
    platform: 'android',
    year: '2024',
    ruleBroken: 'Google Play Data Safety Section Inconsistency',
    revenueImpact: '$9,200 Lost In-App Purchases • 9 Days Removal',
    daysDowntime: 9,
    sourceType: 'IndieHackers',
    fullStory: `Google Play automated bots crawl Android APKs and DEX files. When an indie developer declared "No Personal Data Collected" on their Play Console questionnaire, the Google scanner detected that their mediation ad SDK and crash reporting library accessed Android ID and coarse location.

Instead of a polite email, Google sent a "Policy Violation Warning - 14 Days to Comply or Removal". The developer submitted an update, but because Google's review queue was backed up, the deadline passed and the app was unlisted for 9 days.`,
    developerQuote: `"Google's automated bot flagged our app because our ad network collected GAID even though we personally didn't store it. When the app went down, our daily revenue dropped from $450/day to $0."`,
    keyTakeaway: 'Your Data Safety Form must accurately match every embedded SDK in build.gradle, not just your first-party backend code.',
    preventionCode: `// StoreGuard Data Safety Matcher
// Automatically cross-references build.gradle dependencies against Google Play data categories.`
  },
  {
    id: 'case_4',
    title: 'The AI Avatar Generative UGC Moderation Trap',
    subtitle: 'App Store rejection under Guideline 1.2 for allowing AI prompt generation without an explicit in-app user flag/block system.',
    appNamePlaceholder: 'AI Portrait & Headshot Generator',
    category: 'ugc_moderation',
    platform: 'ios',
    year: '2025',
    ruleBroken: 'Apple Guideline 1.2 (User Generated Content) & AI Policy',
    revenueImpact: '$18,500 Missed Viral Holiday Peak',
    daysDowntime: 12,
    sourceType: 'Twitter',
    fullStory: `A viral AI avatar app was trending on TikTok and ready for a major Black Friday update. Apple rejected the update within 6 hours citing Guideline 1.2: "Apps with user-generated content or AI prompt generation must include a method for filtering objectionable material and a mechanism to report and block offensive outputs."

The developer assumed AI generation wasn't "UGC". Apple clarified that any user-promptable AI output is legally treated as UGC. By the time they built a report modal and content filter, the viral TikTok wave had subsided.`,
    developerQuote: `"We lost our entire viral window because we didn't have a tiny 'Report Image' flag button on our AI results screen. That simple omission cost us an estimated $18k in lifetime value."`,
    keyTakeaway: 'Every generative AI app requires: 1) Automated bad-word filtering, 2) In-app report button, 3) 1-tap block creator, 4) Terms of Service agreement.',
    preventionCode: `// StoreGuard UGC Safety Check:
// Verifies prompt sanitization, EULA acceptance gate, and UI report callbacks.`
  },
  {
    id: 'case_5',
    title: 'The 3.1.1 Anti-Steering Link in FAQ Subpage',
    subtitle: 'A single sentence "Upgrade on our website to save on taxes" buried in help documentation caused 3 consecutive App Store rejections.',
    appNamePlaceholder: 'SaaS Mobile Companion App',
    category: 'paywall_iap',
    platform: 'ios',
    year: '2024',
    ruleBroken: 'Apple Guideline 3.1.1 - In-App Purchase Steering',
    revenueImpact: '$6,400 Lost Pre-orders • 21-Day Review Freeze',
    daysDowntime: 21,
    sourceType: 'Reddit',
    fullStory: `An indie SaaS developer built a companion mobile app. Inside the app's WebView help center, a small FAQ article mentioned "How do I upgrade? You can manage your subscription on web or use In-App Purchase."

An Apple manual reviewer tested the link, opened the web checkout, and flagged the app for violating anti-steering rules. Because the developer argued with the reviewer in Resolution Center instead of removing the link, the app was placed in extended review limbo for 3 weeks.`,
    developerQuote: `"Do NOT argue with App Store reviewers over 3.1.1. One tiny link in a help article delayed our product release by almost a month."`,
    keyTakeaway: 'Audit all in-app WebViews, terms, and external URLs before submitting to ensure zero forbidden payment references.',
    preventionCode: `// StoreGuard Crawler:
// Recursively audits all external URLs and in-app strings for steering keywords.`
  },
  {
    id: 'case_6',
    title: 'Vague Purpose String (NSCameraUsageDescription) Rejection',
    subtitle: '"Camera is required for app functionality" triggered an immediate App Store rejection.',
    appNamePlaceholder: 'Receipt Scanner & Budget Tracker',
    category: 'permissions',
    platform: 'ios',
    year: '2025',
    ruleBroken: 'Apple Guideline 5.1.1 - Purpose String Specificity',
    revenueImpact: '$1,200 Delay Cost • 4-Day Launch Slip',
    daysDowntime: 4,
    sourceType: 'Reddit',
    fullStory: `A first-time indie developer wrote generic placeholder descriptions in Info.plist during prototyping. When shipping the release version, they forgot to update NSCameraUsageDescription.

Apple review automated checker flagged the purpose string as non-compliant because it failed to state the exact user-facing utility (scanning physical receipts).`,
    developerQuote: `"A 10-word sentence in Info.plist delayed my launch for 4 days. Now I run StoreGuard on every commit to make sure nothing slipped through."`,
    keyTakeaway: 'Permission strings must explain why the app needs access and what feature it powers, written in clear user-friendly language.',
    preventionCode: `<key>NSCameraUsageDescription</key>
<string>Allows you to snap photos of receipts for automated OCR expense categorization.</string>`
  }
];
